[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
build_flags = -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
lib_deps =
    ZinggJM/GxEPD2 @ ^1.6.0
