; CH32V003 Thermal Haptics
; MAX4466 beat detection -> coin vibration motor + guarded Peltier PWM

[env:genericCH32V003F4P6]
platform = ch32v
board = genericCH32V003F4P6
framework = ch32v003fun
upload_protocol = wch-link
monitor_speed = 115200

; Optional alternatives:
; upload_protocol = minichlink
; upload_protocol = wlink
