[env:esp32dev]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED

[env:esp32c3]
platform = espressif32@6.6.0
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    ${env:esp32dev.lib_deps}
